/*
 * Copyright (c) 2010, Oracle. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Oracle nor the names of its contributors
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.kalman;

import com.kalman.lang.Config;
import com.kalman.lang.FileChooserEvent;
import com.kalman.lang.MybatisBuilder;


public class MainFrame extends javax.swing.JFrame {
 
	private static final long serialVersionUID = 6476814826464109683L;
	/** Creates new form Find */
    public MainFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_url = new javax.swing.JTextField();
        btn_generate = new javax.swing.JButton();
        text_userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label_tips = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_pojoPackage = new javax.swing.JTextField();
        text_password = new javax.swing.JTextField();
        text_mapperPackage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        checkbox_anotation = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        text_outLocation = new javax.swing.JTextField();
        btn_select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mybatis小助手");

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel1.setText("Mapper Package:");

        text_url.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        btn_generate.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btn_generate.setText("Generate");
        btn_generate.setActionCommand("Generate");
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });

        text_userName.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel2.setText("POJO Package:");

        label_tips.setText("<html> 使用说明：<br> 1、默认配置位于该文件同目录<span style=\"color:red\">conf.properties</span>中；<br> 2、有BUG的话请联系南江吧</html>");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel4.setText("JDBC.Password:");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel5.setText("JDBC.UserName:");

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel6.setText("JDBC.URL:");
        jLabel6.setToolTipText("");

        text_pojoPackage.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        text_password.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        text_mapperPackage.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel7.setText("Anotation:");

        checkbox_anotation.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        checkbox_anotation.setText("@Mapper");

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel8.setText("Result location:");

        text_outLocation.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        btn_select.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_select.setText("Select...");
        btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(label_tips))
                    .add(layout.createSequentialGroup()
                        .add(148, 148, 148)
                        .add(btn_generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel6)
                                .add(75, 75, 75)
                                .add(text_url))
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(text_userName))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .add(18, 18, 18)
                                .add(text_password))
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(text_mapperPackage)
                                .add(1, 1, 1))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(text_pojoPackage))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(checkbox_anotation))
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel8)
                                        .add(18, 18, 18)
                                        .add(text_outLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn_select, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(text_url, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(text_userName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(text_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(text_mapperPackage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(text_pojoPackage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(checkbox_anotation))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel8)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(text_outLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(btn_select)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(btn_generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(label_tips, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
        );

        initData();
        pack();
    }// </editor-fold>                        

    
    private void initData(){
    	this.text_mapperPackage.setText(Config.getMapperPackage());
    	this.text_outLocation.setText(Config.getResultLocation());
    	this.text_password.setText(Config.getPassword());
    	this.text_pojoPackage.setText(Config.getPojoPackage());
    	this.text_url.setText(Config.getUrl());
    	this.text_userName.setText(Config.getUserName());
    	this.checkbox_anotation.setSelected(Config.getAnotationOrNot());
    }
    
    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	try {
    		GConfig.FILE_SAVE_PATH = this.text_outLocation.getText();
        	GConfig.M_PACKAGE = this.text_mapperPackage.getText();
        	GConfig.P_PACKAGE=this.text_pojoPackage.getText();
        	GConfig.MYSQL_CONNECTION_URL = this.text_url.getText()+"?user="+this.text_userName.getText()+"&password="+this.text_password.getText();
        	this.label_tips.setText("操作进行中.......");
        	MybatisBuilder.build();
        	this.label_tips.setText("操作成功，文件保存在--->"+GConfig.FILE_SAVE_PATH);
		} catch (Exception e) {
			this.label_tips.setText(e.getMessage());
		}
    }                                            

    private void btn_selectActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	String filePath = new FileChooserEvent(evt).getFilePath();
    	this.text_outLocation.setText(filePath);
    }                                          
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_generate;
    private javax.swing.JButton btn_select;
    private javax.swing.JCheckBox checkbox_anotation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_tips;
    private javax.swing.JTextField text_mapperPackage;
    private javax.swing.JTextField text_outLocation;
    private javax.swing.JTextField text_password;
    private javax.swing.JTextField text_pojoPackage;
    private javax.swing.JTextField text_url;
    private javax.swing.JTextField text_userName;
    // End of variables declaration                   
    
}
